In [53]:
from lbpqca.lattice.reductions_lattice import LLL, BKZ, babai_nearest_plane
from lbpqca.lattice.attacks import BDD_atack, BDD_atack_recovery_secret, SVP_atack, SVP_atack_recovery_secret
from lbpqca.lattice.reductions_problems import LWR_to_LWE
import numpy as np


In [54]:
A=np.array([[ 4, 13, 11,  0,  6],
 [14,  11,  0, 1, 12],
 [14,  2,  1, 14,  0],
 [ 9,  1,  5,  8,  7],
 [ 6,  0,  0,  2,  0],
 [11,  8, 11,  15, 10],
 [12,  6,  7, 16, 13],
 [15,  6, 11, 17, 11],
 [14, 11, 11,  6, 14],
 [ 2,  9, 11, 11,  8]],dtype=int)

m, n, q, p = 10, 5, 47, 30

s=np.array([0,2,4,5,1],dtype=int)

b=np.round(A@s*(p/q)).astype(int)

print('A=',A,'\nb=',b)


A= [[ 4 13 11  0  6]
 [14 11  0  1 12]
 [14  2  1 14  0]
 [ 9  1  5  8  7]
 [ 6  0  0  2  0]
 [11  8 11 15 10]
 [12  6  7 16 13]
 [15  6 11 17 11]
 [14 11 11  6 14]
 [ 2  9 11 11  8]] 
b= [49 25 50 44  6 93 85 97 70 80]


In [55]:
Ae, be = LWR_to_LWE(A, b, p, q)
print('Ae=',Ae,'\nbe=',be)

Ae= [[ 4 13 11  0  6]
 [14 11  0  1 12]
 [14  2  1 14  0]
 [ 9  1  5  8  7]
 [ 6  0  0  2  0]
 [11  8 11 15 10]
 [12  6  7 16 13]
 [15  6 11 17 11]
 [14 11 11  6 14]
 [ 2  9 11 11  8]] 
be= [ 77  39  78  69   9 146 133 152 110 125]


In [56]:
tt=(be-A@s)%q
print(tt)

[ 1  0  0  0 46  1  0  0  0  0]


In [57]:
h=SVP_atack(Ae,be,q)
print("Kannan's embedding")
print(h)

Kannan's embedding
[[ 1  0  0  0  0  0 41 15  0 22 18]
 [ 0  1  0  0  0  0  7 25 32  7 13]
 [ 0  0  1  0  0  0 41 43 12 14 43]
 [ 0  0  0  1  0  0  0 23 15  6 20]
 [ 0  0  0  0  1  0 14  8 23 44 33]
 [ 0  0  0  0  0  1 20 40 23 22 16]
 [ 0  0  0  0  0  0 47  0  0  0  0]
 [ 0  0  0  0  0  0  0 47  0  0  0]
 [ 0  0  0  0  0  0  0  0 47  0  0]
 [ 0  0  0  0  0  0  0  0  0 47  0]
 [ 0  0  0  0  0  0  0  0  0  0 47]]


In [58]:
x=BKZ(h,20)
print('Reduces basis')
print(x)

Reduces basis
[[-1  0  0  0  1 -1  0  0  0  0 -1]
 [ 0 -3  0 -3  2  2  0 -1 -2 -1 -1]
 [-1 -1 -1  3  1 -1 -1  1  1 -3  3]
 [-3 -1 -1  0  2  0 -2 -3  2  1  3]
 [ 4  1  1  0 -1 -3 -3  0 -1 -1  0]
 [ 1  4  0  1  2  2 -4 -1  0  0  0]
 [-3  1  2  1 -2  3 -2  5  0  0  0]
 [ 0  0  4  0  2  0  4  0  0  3  3]
 [-1  1  0  2 -1  0 -1  1 -8  0  2]
 [ 3 -4 -4 -2  5  0  1  2  3  2  2]
 [-1 -4  1  6 -1  2 -2 -3 -3  0 -2]]


In [60]:
sw1=SVP_atack_recovery_secret(Ae,be,x[0],q)
print("recovered secret:")
print(sw1)
print("true secret:")
print(s)

recovered secret:
[0 2 4 5 1]
true secret:
[0 2 4 5 1]
