In [1]:
from lbpqca.lattice.reductions_lattice import LLL, BKZ, babai_nearest_plane
from lbpqca.lattice.attacks import BDD_atack, BDD_atack_recovery_secret, SVP_atack, SVP_atack_recovery_secret
from lbpqca.lattice.reductions_problems import RLWE_to_LWE
from lbpqca.polynomial import add_poly, mull_poly
import numpy as np

In [2]:
A=np.array([[ [4, 11, 3], [0,  6, 7]],
 [[14,  5,  0], [1, 12, 6]],
 [ [9,  1,  5],  [8,  7, 11]]],dtype=int)

m, n, k, q = 3, 2, 3, 17

e=np.array([ [0, 1,  0],  [0,  0, -1], [1, 0, 1]],dtype=int)

s=np.array([[2,2,4],[5,1,3]],dtype=int)

tmp=[]

for i in range(m):
    l = e[i].copy()
    for j in range(n):
        l=add_poly(l, mull_poly(A[i,j],s[j], q), q)
    tmp.append(l)

b=np.array(tmp,dtype=int)

print('A=',A,'\nb=',b)



A= [[[ 4 11  3]
  [ 0  6  7]]

 [[14  5  0]
  [ 1 12  6]]

 [[ 9  1  5]
  [ 8  7 11]]] 
b= [[ 1 11  0]
 [ 5 13  8]
 [13 10 16]]


In [3]:
Ae, be = RLWE_to_LWE(A,b,q)
Ae=Ae.astype(int)
print('Ae=',Ae,'\nbe=',be)

Ae= [[  4  -3 -11   0  -7  -6]
 [ 11   4  -3   6   0  -7]
 [  3  11   4   7   6   0]
 [ 14   0  -5   1  -6 -12]
 [  5  14   0  12   1  -6]
 [  0   5  14   6  12   1]
 [  9  -5  -1   8 -11  -7]
 [  1   9  -5   7   8 -11]
 [  5   1   9  11   7   8]] 
be= [ 1 11  0  5 13  8 13 10 16]


In [4]:
print((Ae@s.flatten()-be)%q)

[ 0 16  0  0  0  1 16  0 16]


In [5]:
h=SVP_atack(Ae,be,q)
print("Kannan's embedding")
print(h)

Kannan's embedding
[[ 1  0  0  0  0  0  0 11  0  1]
 [ 0  1  0  0  0  0  0 14  8 15]
 [ 0  0  1  0  0  0  0  7  3  3]
 [ 0  0  0  1  0  0  0  8  1  2]
 [ 0  0  0  0  1  0  0 16  1  7]
 [ 0  0  0  0  0  1  0  9  5  0]
 [ 0  0  0  0  0  0  1 12 15  3]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 17  0]
 [ 0  0  0  0  0  0  0  0  0 17]]


In [6]:
x=BKZ(h,20)
print('Reduces basis')
print(x)

Reduces basis
[[ 0 -1  0  0  0  1 -1  0 -1 -1]
 [ 1  0 -1 -1  1  0 -1  0 -1  0]
 [-1  0  1  1  0 -1 -1  0  1  1]
 [ 0  1 -1  1  0 -1  1  1 -1  0]
 [-1  0 -2  0  1  1  0  0  0  0]
 [ 1 -1  0  0 -1 -1  1  1  1 -1]
 [ 1 -1 -1  0  0 -1  0 -2  1  0]
 [ 1  0  0  0 -2  0 -1  1  0  1]
 [ 0 -2  1 -1 -1  0  1  1  0  1]
 [ 0 -1  0  1  2  1  0  1  0  1]]


In [8]:
sw1=SVP_atack_recovery_secret(Ae,be,x[0],q)
print("recovered secret:")
print(sw1.reshape((n,k)))
print("true secret:")
print(s)

recovered secret:
[[2 2 4]
 [5 1 3]]
true secret:
[[2 2 4]
 [5 1 3]]
