In [5]:
from lbpqca.lattice.reductions_lattice import BKZ
from lbpqca.lattice.attacks import dual_lattice_atack
import numpy as np
import math

In [9]:
A=np.array([[ 4, 13, 11,  0,  6],
 [14,  9,  0, 1, 12],
 [14,  2,  1, 14,  0],
 [ 9,  1,  5,  8,  7],
 [ 6,  0,  0,  2,  0],
 [11,  8, 11,  15, 10],
 [12,  6,  7, 16, 13],
 [16,  6, 11, 16, 11],
 [14, 11, 11,  6, 14],
 [ 2,  9, 12, 14,  8]],dtype=int)

m, n, q = 10, 5, 17

e=np.array([ 0, 0,  1,  0,  0, 0, -1, -1, 0, 1],dtype=int)

s=np.array([2,2,0,2,1],dtype=int)

b=A@s+e
posible=[0,1,2]

print('A=',A,'\nb=',b)

A= [[ 4 13 11  0  6]
 [14  9  0  1 12]
 [14  2  1 14  0]
 [ 9  1  5  8  7]
 [ 6  0  0  2  0]
 [11  8 11 15 10]
 [12  6  7 16 13]
 [16  6 11 16 11]
 [14 11 11  6 14]
 [ 2  9 12 14  8]] 
b= [40 60 61 43 16 78 80 86 76 59]


In [10]:
recovered_secret = []

print(f"Recovering secret's components")
for i in range(n):
    A_punctured = np.delete(A, i, axis=1)
    G_dual = dual_lattice_atack(A_punctured, q)
    target_column = A[:, i]
    v = BKZ(G_dual, 10)[0]
    inter = np.dot(v, target_column)

    best_guess = 0
    max_score = -float('inf')

    proj = np.dot(v, b)

    for guess in posible:

        cor = guess * inter
        score = math.cos((2 * math.pi * ((proj - cor) % q)) / q)

        if score > max_score:
            max_score = score
            best_guess = guess

    recovered_secret.append(best_guess)

print()
print("Real secret:")
print(s)
print("Recovered secret:")
print(recovered_secret)

Recovering secret's components

Real secret:
[2 2 0 2 1]
Recovered secret:
[2, 2, 0, 2, 1]
