In [61]:
from lbpqca.lattice.reductions_lattice import BKZ
from lbpqca.lattice.attacks import SVP_atack, SVP_atack_recovery_secret
from lbpqca.lattice.reductions_problems import LWR_to_LWE
import numpy as np

In [62]:
A=np.array([[ 4, 13, 11,  0,  6],
 [14,  11,  0, 1, 12],
 [14,  2,  1, 14,  0],
 [ 9,  1,  5,  8,  7],
 [ 6,  0,  0,  2,  0],
 [11,  8, 11,  15, 10],
 [12,  6,  7, 16, 13],
 [16,  6, 11, 16, 11],
 [14, 11, 11,  6, 14],
 [ 2,  9, 12, 14,  8]],dtype=int)

m, n, q, p = 10, 5, 17, 2

s=np.array([0,2,4,5,1],dtype=int)

b=np.round(A@s*(p/q)).astype(int)

print('A=',A,'\nb=',b)


A= [[ 4 13 11  0  6]
 [14 11  0  1 12]
 [14  2  1 14  0]
 [ 9  1  5  8  7]
 [ 6  0  0  2  0]
 [11  8 11 15 10]
 [12  6  7 16 13]
 [16  6 11 16 11]
 [14 11 11  6 14]
 [ 2  9 12 14  8]] 
b= [ 9  5  9  8  1 17 16 17 13 17]


In [63]:
Ae, be = LWR_to_LWE(A, b, p, q)
print('Ae=',Ae,'\nbe=',be)

Ae= [[ 4 13 11  0  6]
 [14 11  0  1 12]
 [14  2  1 14  0]
 [ 9  1  5  8  7]
 [ 6  0  0  2  0]
 [11  8 11 15 10]
 [12  6  7 16 13]
 [16  6 11 16 11]
 [14 11 11  6 14]
 [ 2  9 12 14  8]] 
be= [ 72  40  72  64   8 136 128 136 104 136]


In [64]:
h=SVP_atack(Ae,be,q)
print("Kannan's embedding")
print(h)

Kannan's embedding
[[ 1  0  0  0  0  0  9  9  5  5  5]
 [ 0  1  0  0  0  0 14 14 11  9  8]
 [ 0  0  1  0  0  0 16  7 12  3  4]
 [ 0  0  0  1  0  0  9  4  2  5  2]
 [ 0  0  0  0  1  0  6  9 10 13 14]
 [ 0  0  0  0  0  1  0  5 11  9  3]
 [ 0  0  0  0  0  0 17  0  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0  0 17  0]
 [ 0  0  0  0  0  0  0  0  0  0 17]]


In [65]:
x=BKZ(h,10)
print('Reduces basis')
print(x)

Reduces basis
[[-1 -1  1  0  1 -2 -1  0  1  1 -1]
 [ 1  0 -1  1  0 -1  2  1  1 -2  0]
 [-2  0  0  2  0  2  0  0 -1  1  0]
 [-1  0 -1 -3  0 -1 -1  1  0  2 -1]
 [-1  0  0  0 -1  0  2 -1  2 -1 -2]
 [-2  2 -1 -1  0  0  2 -1 -2  0  0]
 [-1 -1  0 -2  1  1 -1  0  1 -2  0]
 [ 2 -1  0 -1  1  1  1 -3  1  1  0]
 [ 0 -3  1  1  0  0  0  3 -2 -2 -1]
 [ 2 -1 -2  0 -1  0  0 -2 -1 -1 -3]
 [-2 -3  0  0 -1  0  2 -1 -2  1  3]]


In [66]:
sw1=SVP_atack_recovery_secret(Ae,be,x[0],q)
print("recovered secret:")
print(sw1)
print("true secret:")
print(s)

recovered secret:
[ 5  2 10 15  0]
true secret:
[0 2 4 5 1]


The secret could not be recovered because the value increased too much for such small data.